import { AdventureApiError } from '../../api/adventures'
import { RoomAssetApiError } from '../../api/roomAssets'
import type { Locale } from '../../i18n/locale'

const COPY = {
  en: {
    title: 'Adventures',
    intro: 'Adventures are reusable world and adventure data packs that a Campaign may attach; Players never see them directly.',
    createTitle: 'Create Adventure',
    nameLabel: 'Adventure name',
    summaryLabel: 'Summary (optional)',
    createAction: 'Create Adventure',
    open: 'Open',
    finalize: 'Finalize',
    archive: 'Archive',
    delete: 'Delete',
    deleteConfirm: 'Delete this Adventure permanently? This action cannot be undone.',
    archiveConfirm: 'Archive this Adventure? Archived Adventures cannot be attached to new Campaigns.',
    statusLabel: 'Status',
    statusDraft: 'Draft',
    statusFinalized: 'Finalized',
    statusArchived: 'Archived',
    empty: 'No Adventures yet.',
    loading: 'Loading Adventures…',
    missingAccess: 'This browser does not have access to this Room. Enter the Room again.',
    requestFailed: 'Adventure request failed.',
    noAuthority: 'Only the Room owner or DM can manage Adventures.',
    backRoom: '← Back to Room workspace',
    backAdventures: '← Back to Adventures',
    editorTitle: 'Adventure Editor',
    definitionTitle: 'Adventure Details',
    saveDefinition: 'Save Details',
    entriesTitle: 'Adventure Entries',
    entriesEmpty: 'No entries yet.',
    addEntryTitle: 'Add Entry',
    editEntryTitle: 'Edit Entry',
    entryKindLabel: 'Kind',
    entryTitleLabel: 'Title (optional)',
    entryBodyLabel: 'Body (optional)',
    entryVisibilityLabel: 'Visibility',
    visibilityPublic: 'Public (DM may narrate)',
    visibilityDmOnly: 'DM only',
    entryParentLabel: 'Parent section (optional)',
    entryParentNone: '(None)',
    saveEntry: 'Save Entry',
    addEntry: 'Add Entry',
    cancelEdit: 'Cancel',
    editEntry: 'Edit',
    deleteEntry: 'Delete',
    entryDeleteConfirm: 'Delete this entry permanently? This action cannot be undone.',
    moveUp: 'Move up',
    moveDown: 'Move down',
    readOnlyNotice: 'This Adventure is archived and read-only.',
    fieldReadAloud: 'Read aloud text',
    fieldDmSummary: 'DM summary',
    fieldRole: 'Role',
    fieldDisposition: 'Disposition',
    fieldRarity: 'Rarity',
    fieldValueGp: 'Value (gp)',
    fieldIsMagic: 'Magic item',
    fieldMonsterTemplateRef: 'Monster template reference',
    fieldCount: 'Count',
    fieldNotes: 'Notes',
    fieldObjective: 'Objective',
    fieldReward: 'Reward',
    fieldRevealCondition: 'Reveal condition',
    fieldAbility: 'Ability',
    fieldSkill: 'Skill (optional)',
    fieldDc: 'DC',
    fieldOnSuccess: 'On success',
    fieldOnFailure: 'On failure',
    fieldCaption: 'Caption',
    fieldTopic: 'Topic',
    dispositionFriendly: 'Friendly',
    dispositionNeutral: 'Neutral',
    dispositionHostile: 'Hostile',
    dispositionUnknown: 'Unknown',
    abilityStr: 'Strength',
    abilityDex: 'Dexterity',
    abilityCon: 'Constitution',
    abilityInt: 'Intelligence',
    abilityWis: 'Wisdom',
    abilityCha: 'Charisma',
    kindSection: 'Section',
    kindScene: 'Scene',
    kindNpc: 'NPC',
    kindItem: 'Item',
    kindMonsterRef: 'Monster Reference',
    kindQuest: 'Quest',
    kindSecret: 'Secret',
    kindDmNote: 'DM Note',
    kindSuggestedCheck: 'Suggested Check',
    kindMap: 'Map',
    kindLore: 'Lore',
    kindOther: 'Other',
    errAdventureNotFound: 'Adventure not found.',
    errAdventureArchived: 'This Adventure is archived and cannot be modified.',
    errAdventureStatusConflict: 'Adventure status conflict.',
    errAdventureAttachedUseArchive: 'This Adventure is attached to one or more Campaigns. Archive it instead of deleting.',
    errAdventureNotFinalized: 'Only finalized Adventures can be attached to a Campaign.',
    errAdventureAlreadyAttached: 'This Adventure is already attached to this Campaign.',
    errAdventureEntryPayloadInvalid: 'Entry fields are invalid; check required fields and numbers.',
    errAdventureEntryParentInvalid: 'Parent entry is invalid (missing or would create a cycle).',
    errAdventureEntryNotFound: 'Adventure entry not found.',
    errAssetVisibilityNotAllowed: 'Asset visibility is not allowed.',
    errAssetInUse: 'Asset is currently in use and cannot be deleted.',
    errAssetMediaTypeNotSupported: 'Asset media type is not supported.',
    errAssetTooLarge: 'Asset file is too large.',
    errRoomAssetNotFound: 'Room asset not found.',
    errAssetEmpty: 'Asset file is empty.',
    assetsTitle: 'Images',
    assetFileLabel: 'Image file (PNG / JPEG / WebP, max 20 MiB)',
    assetRoleLabel: 'Role',
    roleImage: 'Image',
    roleMap: 'Map',
    assetVisibilityLabel: 'Visibility',
    assetVisibilityRoom: 'Room (visible to Players when shown)',
    assetVisibilityDmOnly: 'DM only',
    assetDmOnly: 'DM only',
    uploadAttach: 'Upload & attach',
    unlinkAsset: 'Unlink',
    unlinkConfirm: 'Unlink this image from the entry? The file stays in the Room.',
    attachedTitle: 'Attached Adventures',
    attachedIntro: 'Attaching an Adventure gives this Campaign access to its data; it never copies or edits the Adventure.',
    attachedEmpty: 'No Adventures attached to this Campaign yet.',
    attachPicker: 'Attach a finalized Adventure',
    attachAction: 'Attach',
    detach: 'Detach',
    detachConfirm: 'Detach this Adventure from the Campaign? The Adventure itself is not changed or deleted.',
    noAttachable: 'No finalized Adventure is available to attach.',
    goToAdventures: 'Manage Adventures',
    errCampaignAdventureLinkNotFound: 'This Adventure is not attached to this Campaign.',
    errCampaignAdventureDetachBlocked: 'Cannot detach this Adventure because it has active overrides or is the active scene.',
    errCampaignNotFound: 'Campaign not found.',
  },
  'zh-TW': {
    title: '冒險故事',
    intro: '冒險故事是可重複使用的世界與冒險內容，可供戰役附加；玩家無法直接看見。',
    createTitle: '建立冒險故事',
    nameLabel: '冒險故事名稱',
    summaryLabel: '摘要（選填）',
    createAction: '建立冒險故事',
    open: '開啟',
    finalize: '定稿',
    archive: '封存',
    delete: '刪除',
    deleteConfirm: '要永久刪除此冒險故事嗎？此動作無法復原。',
    archiveConfirm: '要封存此冒險故事嗎？已封存的冒險故事無法附加至新的戰役。',
    statusLabel: '狀態',
    statusDraft: '草稿',
    statusFinalized: '已定稿',
    statusArchived: '已封存',
    empty: '目前還沒有冒險故事。',
    loading: '正在載入冒險故事…',
    missingAccess: '這個瀏覽器沒有此房間的存取權，請重新進入房間。',
    requestFailed: '冒險故事請求失敗。',
    noAuthority: '只有房間 Owner 或 DM 可以管理冒險故事。',
    backRoom: '← 回房間工作區',
    backAdventures: '← 回冒險故事列表',
    editorTitle: '冒險故事編輯器',
    definitionTitle: '冒險故事詳細資訊',
    saveDefinition: '儲存詳細資訊',
    entriesTitle: '冒險資料包',
    entriesEmpty: '目前還沒有資料包。',
    addEntryTitle: '新增資料包',
    editEntryTitle: '編輯資料包',
    entryKindLabel: '類型',
    entryTitleLabel: '標題（選填）',
    entryBodyLabel: '內容（選填）',
    entryVisibilityLabel: '可見度',
    visibilityPublic: '公開（DM 可直接敘事）',
    visibilityDmOnly: '僅 DM',
    entryParentLabel: '上層章節（選填）',
    entryParentNone: '（無）',
    saveEntry: '儲存資料包',
    addEntry: '新增資料包',
    cancelEdit: '取消',
    editEntry: '編輯',
    deleteEntry: '刪除',
    entryDeleteConfirm: '要永久刪除此資料包嗎？此動作無法復原。',
    moveUp: '上移',
    moveDown: '下移',
    readOnlyNotice: '此冒險故事已封存，僅供檢視。',
    fieldReadAloud: '朗讀文字',
    fieldDmSummary: 'DM 摘要',
    fieldRole: '角色',
    fieldDisposition: '態度',
    fieldRarity: '稀有度',
    fieldValueGp: '價值（gp）',
    fieldIsMagic: '魔法物品',
    fieldMonsterTemplateRef: '怪物範本參照',
    fieldCount: '數量',
    fieldNotes: '備註',
    fieldObjective: '目標',
    fieldReward: '獎勵',
    fieldRevealCondition: '揭露條件',
    fieldAbility: '屬性',
    fieldSkill: '技能（選填）',
    fieldDc: 'DC',
    fieldOnSuccess: '成功時',
    fieldOnFailure: '失敗時',
    fieldCaption: '說明',
    fieldTopic: '主題',
    dispositionFriendly: '友善',
    dispositionNeutral: '中立',
    dispositionHostile: '敵對',
    dispositionUnknown: '未知',
    abilityStr: '力量',
    abilityDex: '敏捷',
    abilityCon: '體質',
    abilityInt: '智力',
    abilityWis: '感知',
    abilityCha: '魅力',
    kindSection: '章節',
    kindScene: '場景',
    kindNpc: 'NPC',
    kindItem: '道具',
    kindMonsterRef: '怪物參照',
    kindQuest: '任務',
    kindSecret: '秘密',
    kindDmNote: 'DM 筆記',
    kindSuggestedCheck: '建議檢定',
    kindMap: '地圖',
    kindLore: '背景知識',
    kindOther: '其他',
    errAdventureNotFound: '找不到此冒險故事。',
    errAdventureArchived: '此冒險故事已封存，無法修改。',
    errAdventureStatusConflict: '冒險故事狀態衝突。',
    errAdventureAttachedUseArchive: '此冒險故事已附加至一個或多個戰役，請改用封存而非刪除。',
    errAdventureNotFinalized: '只有已定稿的冒險故事才能附加至戰役。',
    errAdventureAlreadyAttached: '此冒險故事已附加至此戰役。',
    errAdventureEntryPayloadInvalid: '資料包欄位無效，請檢查必填欄位與數字。',
    errAdventureEntryParentInvalid: '上層資料包無效（不存在或會形成循環）。',
    errAdventureEntryNotFound: '找不到此冒險資料包。',
    errAssetVisibilityNotAllowed: '不允許的素材可見度。',
    errAssetInUse: '素材目前正在使用中，無法刪除。',
    errAssetMediaTypeNotSupported: '不支援的素材檔案類型。',
    errAssetTooLarge: '素材檔案過大。',
    errRoomAssetNotFound: '找不到此房間素材。',
    errAssetEmpty: '素材檔案為空。',
    assetsTitle: '圖片',
    assetFileLabel: '圖片檔（PNG／JPEG／WebP，上限 20 MiB）',
    assetRoleLabel: '用途',
    roleImage: '圖片',
    roleMap: '地圖',
    assetVisibilityLabel: '可見度',
    assetVisibilityRoom: '房間（顯示時玩家可見）',
    assetVisibilityDmOnly: '僅 DM',
    assetDmOnly: '僅 DM',
    uploadAttach: '上傳並附加',
    unlinkAsset: '解除連結',
    unlinkConfirm: '要解除此圖片與資料包的連結嗎？檔案仍保留在房間。',
    attachedTitle: '已附加的冒險故事',
    attachedIntro: '附加冒險故事可讓此戰役存取其資料；這絕不會複製或修改冒險故事本身。',
    attachedEmpty: '此戰役尚未附加任何冒險故事。',
    attachPicker: '附加已定稿的冒險故事',
    attachAction: '附加',
    detach: '解除附加',
    detachConfirm: '要解除此冒險故事與戰役的附加嗎？冒險故事本身不會被修改或刪除。',
    noAttachable: '目前沒有可附加的已定稿冒險故事。',
    goToAdventures: '管理冒險故事',
    errCampaignAdventureLinkNotFound: '此冒險故事未附加至此戰役。',
    errCampaignAdventureDetachBlocked: '無法解除附加此冒險故事，因為其具有作用中的覆寫或為目前場景。',
    errCampaignNotFound: '找不到此戰役。',
  },
} as const satisfies Record<Locale, Record<string, string>>

export function adventuresCopy(locale: Locale) {
  return COPY[locale]
}

export function adventureErrorMessage(
  error: unknown,
  copy: ReturnType<typeof adventuresCopy>,
): string {
  const code =
    error instanceof AdventureApiError || error instanceof RoomAssetApiError
      ? error.code
      : typeof error === 'object' && error !== null && 'code' in error
        ? String((error as { code: unknown }).code)
        : null

  switch (code) {
    case 'adventure_not_found':
      return copy.errAdventureNotFound
    case 'adventure_archived':
      return copy.errAdventureArchived
    case 'adventure_status_conflict':
      return copy.errAdventureStatusConflict
    case 'adventure_attached_use_archive':
      return copy.errAdventureAttachedUseArchive
    case 'adventure_not_finalized':
      return copy.errAdventureNotFinalized
    case 'adventure_already_attached':
      return copy.errAdventureAlreadyAttached
    case 'adventure_entry_payload_invalid':
      return copy.errAdventureEntryPayloadInvalid
    case 'adventure_entry_parent_invalid':
      return copy.errAdventureEntryParentInvalid
    case 'adventure_entry_not_found':
      return copy.errAdventureEntryNotFound
    case 'asset_visibility_not_allowed':
      return copy.errAssetVisibilityNotAllowed
    case 'asset_in_use':
      return copy.errAssetInUse
    case 'asset_media_type_not_supported':
      return copy.errAssetMediaTypeNotSupported
    case 'asset_too_large':
      return copy.errAssetTooLarge
    case 'room_asset_not_found':
      return copy.errRoomAssetNotFound
    case 'asset_empty':
      return copy.errAssetEmpty
    case 'campaign_adventure_link_not_found':
      return copy.errCampaignAdventureLinkNotFound
    case 'campaign_adventure_detach_blocked':
      return copy.errCampaignAdventureDetachBlocked
    case 'campaign_not_found':
      return copy.errCampaignNotFound
    default:
      return copy.requestFailed
  }
}
