import type { Locale } from '../../i18n/locale'

const COPY = {
  en: {
    campaignsTitle: 'Campaigns',
    campaignsIntro: 'Campaigns group the Room characters that participate in the same ongoing game. Character Build and Current State are never copied.',
    createTitle: 'Create Campaign',
    nameLabel: 'Campaign name',
    rulesetLabel: 'Ruleset',
    createAction: 'Create Campaign',
    selected: 'Selected for this Room',
    select: 'Select Campaign',
    clearSelection: 'Clear selection',
    open: 'Open Campaign',
    openLobby: 'Open Lobby',
    status: 'Status',
    rosterTitle: 'Party Roster',
    rosterIntro: 'Roster status belongs to the Campaign. HP, inventory, prepared spells, and resources still belong to the one shared Character.',
    addCharacter: 'Add Character',
    levelLabel: 'Level',
    addAction: 'Add to Roster',
    remove: 'Remove',
    removeConfirm: 'Remove this Character from the Party Roster? Re-adding it later will create a new roster entry.',
    noCampaigns: 'No Campaigns yet.',
    noRoster: 'No Characters in this roster yet.',
    noCharacters: 'No available Room Characters to add.',
    backRoom: '← Back to Room workspace',
    backCampaigns: '← Back to Campaigns',
    loading: 'Loading Campaigns…',
    missingAccess: 'This browser does not have access to this Room. Enter the Room again.',
    requestFailed: 'Campaign request failed.',
    ownerLifecycleHint: 'Campaign lifecycle is Owner-only. DM authority may manage the Party Roster but cannot create, archive, select, or delete Campaigns.',
    deleteDraft: 'Delete draft Campaign',
    draft: 'Draft',
    active: 'Active',
    completed: 'Completed',
    archived: 'Archived',
    rosterActive: 'Active',
    inactive: 'Inactive',
    retired: 'Retired',
    dead: 'Dead',
  },
  'zh-TW': {
    campaignsTitle: 'Campaigns',
    campaignsIntro: 'Campaign 用來整理同一場長期遊戲中參與的 Room 角色；角色 Build 與 Current State 不會被複製。',
    createTitle: '建立 Campaign',
    nameLabel: 'Campaign 名稱',
    rulesetLabel: '規則集',
    createAction: '建立 Campaign',
    selected: '目前 Room 選中的 Campaign',
    select: '選為目前 Campaign',
    clearSelection: '清除目前選擇',
    open: '開啟 Campaign',
    openLobby: '進入大廳',
    status: '狀態',
    rosterTitle: '隊伍名冊',
    rosterIntro: '名冊狀態屬於 Campaign；HP、道具、已準備法術與資源仍然只存在同一份角色 Current State。',
    addCharacter: '加入角色',
    levelLabel: '等級',
    addAction: '加入名冊',
    remove: '移除',
    removeConfirm: '要從隊伍名冊移除此角色嗎？稍後重新加入會建立新的名冊項目。',
    noCampaigns: '目前還沒有 Campaign。',
    noRoster: '目前名冊中沒有角色。',
    noCharacters: '沒有可加入的 Room 角色。',
    backRoom: '← 回 Room 工作區',
    backCampaigns: '← 回 Campaign 列表',
    loading: '正在載入 Campaign…',
    missingAccess: '這個瀏覽器沒有此 Room 的存取權，請重新進入 Room。',
    requestFailed: 'Campaign 請求失敗。',
    ownerLifecycleHint: 'Campaign lifecycle 只有 Owner 可管理。DM 權限可以管理隊伍名冊，但不能建立、封存、選擇或刪除 Campaign。',
    deleteDraft: '刪除草稿 Campaign',
    draft: '草稿',
    active: '進行中',
    completed: '已完成',
    archived: '已封存',
    rosterActive: '啟用',
    inactive: '未啟用',
    retired: '退休',
    dead: '死亡',
  },
} as const satisfies Record<Locale, Record<string, string>>

export function campaignCopy(locale: Locale) {
  return COPY[locale]
}
