import type { Locale } from '../../i18n/locale'

const COPY = {
  en: {
    eyebrow: 'P2 · Room workspace',
    title: 'Start at the table',
    description: 'Create a Room for a new table, or enter an existing Room with its code and password.',
    createTitle: 'Create Room',
    roomName: 'Room name',
    password: 'Room password',
    displayName: 'Display name (optional)',
    createAction: 'Create Room',
    enterTitle: 'Enter Room',
    roomCode: 'Room code',
    elevatedKey: 'DM / Owner key (optional)',
    enterAction: 'Enter Room',
    recentTitle: 'Recent Rooms',
    continueAction: 'Open Room',
    createdTitle: 'Room created',
    createdDescription: 'Save these elevated keys now. Adventure Table will not store or show the raw keys again.',
    ownerKey: 'Owner key',
    dmKey: 'DM key',
    roomCodeLabel: 'Room code',
    requestError: 'Room request failed.',
    workspaceEyebrow: 'Room workspace',
    workspaceLoading: 'Opening Room…',
    workspaceMissing: 'This browser does not have an access token for this Room. Enter the Room again from the homepage.',
    workspaceError: 'Room access could not be verified. Enter the Room again if your access expired.',
    workspacePlaceholder: 'Character management is now scoped to this Room. Campaigns, Seats, and Sessions arrive in the next P2 subphases.',
    charactersAction: 'Open Character Workshop',
    authority: 'Room authority',
    backHome: 'Back to Room entry',
    backToWorkspace: '← Back to Room workspace',
    legacyEyebrow: 'Owner migration',
    legacyTitle: 'Legacy Character Data',
    legacyDescription: 'This server still has Character data from before Room scoping. Claiming moves only currently unscoped data into this Room once; already scoped data is never moved.',
    legacyCounts: '{characters} Characters · {drafts} Drafts',
    legacyClaim: 'Claim Legacy Character Data',
    legacyClaiming: 'Claiming…',
    legacyConfirm: 'Claim {characters} Characters and {drafts} Drafts into “{room}”? This one-time action does not move data already assigned to another Room.',
  },
  'zh-TW': {
    eyebrow: 'P2 · Room 工作區',
    title: '先進入跑團房間',
    description: '建立新的 Room，或使用房號與密碼進入既有 Room。',
    createTitle: '建立 Room',
    roomName: 'Room 名稱',
    password: 'Room 密碼',
    displayName: '顯示名稱（選填）',
    createAction: '建立 Room',
    enterTitle: '進入 Room',
    roomCode: 'Room 房號',
    elevatedKey: 'DM / Owner Key（選填）',
    enterAction: '進入 Room',
    recentTitle: '最近使用的 Rooms',
    continueAction: '開啟 Room',
    createdTitle: 'Room 已建立',
    createdDescription: '請現在保存以下進階 Key。Adventure Table 不會保存或再次顯示這些原始 Key。',
    ownerKey: 'Owner Key',
    dmKey: 'DM Key',
    roomCodeLabel: 'Room 房號',
    requestError: 'Room 請求失敗。',
    workspaceEyebrow: 'Room 工作區',
    workspaceLoading: '正在開啟 Room…',
    workspaceMissing: '這個瀏覽器沒有此 Room 的存取權杖，請回首頁重新進入 Room。',
    workspaceError: '無法驗證 Room 存取權限；如果權限已失效，請重新進入 Room。',
    workspacePlaceholder: '角色管理現在已限定於這個 Room；Campaign、Seat 與 Session 會在後續 P2 子階段加入。',
    charactersAction: '開啟角色工作區',
    authority: 'Room 權限',
    backHome: '回 Room 入口',
    backToWorkspace: '← 回 Room 工作區',
    legacyEyebrow: 'Owner 資料移轉',
    legacyTitle: '舊版角色資料',
    legacyDescription: '這台伺服器仍有 Room 化以前的角色資料。領取只會把目前仍未歸屬 Room 的資料一次性放進此 Room；已經屬於其他 Room 的資料不會被搬動。',
    legacyCounts: '{characters} 個角色 · {drafts} 個草稿',
    legacyClaim: '領取舊版角色資料',
    legacyClaiming: '正在領取…',
    legacyConfirm: '要把 {characters} 個角色與 {drafts} 個草稿領取到「{room}」嗎？這是一次性動作，不會搬動已經屬於其他 Room 的資料。',
  },
} as const satisfies Record<Locale, Record<string, string>>

export type RoomCopy = (typeof COPY)[Locale]

export function roomCopy(locale: Locale): RoomCopy {
  return COPY[locale]
}
