import type { Locale } from '../../i18n/locale'

const COPY = {
  en: {
    eyebrow: 'P2 · Room workspace',
    title: 'Start at the table',
    description: 'Create a Room for a new table, or enter an existing Room with its code and password.',
    descriptionHint: '(Room code is generated after creation)',
    createTitle: 'Create Room',
    roomName: 'Room name',
    password: 'Room password',
    displayName: 'Player display name (optional)',
    createAction: 'Create Room',
    enterTitle: 'Enter Room',
    roomCode: 'Room code',
    elevatedKey: 'DM / Owner key (optional)',
    enterAction: 'Enter Room',
    recentTitle: 'Recent Rooms',
    recentRemove: 'Remove “{room}” from Recent Rooms',
    continueAction: 'Open Room',
    createdTitle: 'Room created',
    createdDescription: 'Save these elevated keys now. Adventure Table will not store or show the raw keys again.',
    ownerKey: 'Owner key',
    dmKey: 'DM key',
    roomCodeLabel: 'Room code',
    requestError: 'Room request failed.',
    workspaceEyebrow: 'Room workspace',
    workspaceLoading: 'Opening Room…',
    workspaceMissing: 'This browser does not have an access token for this Room. Enter the Room again from the homepage.',
    workspaceError: 'Room access could not be verified. Enter the Room again if your access expired.',
    workspaceStale: 'This Room no longer exists or its access token is no longer valid. It has been removed from Recent Rooms; enter the Room again from the homepage if it still exists.',
    workspacePlaceholder: 'Characters and Campaign rosters are available in this Room. Seats and Sessions arrive in the next P2 subphases.',
    charactersAction: 'Open Character Workshop',
    campaignsAction: 'Open Campaigns',
    adventuresAction: 'Open Adventures',
    authority: 'Room authority',
    backHome: 'Back to Room entry',
    backToWorkspace: '← Back to Room workspace',
    legacyEyebrow: 'Owner migration',
    legacyTitle: 'Legacy Character Data',
    legacyDescription: 'This server still has Character data from before Room scoping. Claiming moves only currently unscoped data into this Room once; already scoped data is never moved.',
    legacyCounts: '{characters} Characters · {drafts} Drafts',
    legacyClaim: 'Claim Legacy Character Data',
    legacyClaiming: 'Claiming…',
    legacyConfirm: 'Claim {characters} Characters and {drafts} Drafts into “{room}”? This one-time action does not move data already assigned to another Room.',
    deleteRoomTitle: 'Delete Room permanently',
    deleteRoomDescription: 'This permanently deletes this Room workspace, including all Campaigns, Sessions and their event history, Party Rosters, Seats, active Combat, and every Character and Draft in the Room. Export anything you need first.',
    deleteRoomInventorySummary: '{campaigns} Campaigns · {characters} Characters · {drafts} Drafts',
    deleteRoomInventoryCampaigns: 'Campaigns',
    deleteRoomInventoryCharacters: 'Characters',
    deleteRoomInventoryArchivedSuffix: ' (archived)',
    deleteRoomInventoryLoading: 'Loading Room inventory…',
    deleteRoomInventoryError: 'Failed to load Room inventory.',
    deleteRoomAction: 'Delete Room permanently',
    deleteRoomPrompt: 'Type “{room}” to confirm permanent deletion.',
    deleteRoomCancel: 'Cancel',
    deleteRoomConfirm: 'Delete Room',
    deleteRoomDeleting: 'Deleting…',
  },
  'zh-TW': {
    eyebrow: 'P2 · 房間工作區',
    title: '先進入房間',
    description: '建立新的房間，或使用房號與密碼進入既有房間。',
    descriptionHint: '（房號在建立後才會產生）',
    createTitle: '建立房間',
    roomName: '房間名稱',
    password: '房間密碼',
    displayName: '玩家顯示名稱（選填）',
    createAction: '建立房間',
    enterTitle: '進入房間',
    roomCode: '房號',
    elevatedKey: 'DM / Owner Key（選填）',
    enterAction: '進入房間',
    recentTitle: '最近使用的房間',
    recentRemove: '從最近使用的房間移除「{room}」',
    continueAction: '開啟房間',
    createdTitle: '房間已建立',
    createdDescription: '請現在保存以下進階 Key。Adventure Table 不會保存或再次顯示這些原始 Key。',
    ownerKey: 'Owner Key',
    dmKey: 'DM Key',
    roomCodeLabel: '房號',
    requestError: '房間請求失敗。',
    workspaceEyebrow: '房間工作區',
    workspaceLoading: '正在開啟房間…',
    workspaceMissing: '這個瀏覽器沒有此房間的存取權杖，請回首頁重新進入房間。',
    workspaceError: '無法驗證房間存取權限；如果權限已失效，請重新進入房間。',
    workspaceStale: '這個房間已不存在，或存取權杖已失效；已從最近使用的房間移除。若房間仍存在，請回首頁重新進入。',
    workspacePlaceholder: '這個房間現在可以管理角色與戰役名冊；席位與跑團會在後續 P2 子階段加入。',
    charactersAction: '開啟角色工作區',
    campaignsAction: '開啟戰役',
    adventuresAction: '開啟冒險故事',
    authority: '房間權限',
    backHome: '回房間入口',
    backToWorkspace: '← 回房間工作區',
    legacyEyebrow: 'Owner 資料移轉',
    legacyTitle: '舊版角色資料',
    legacyDescription: '這台伺服器仍有房間化以前的角色資料。領取只會把目前仍未歸屬房間的資料一次性放進此房間；已經屬於其他房間的資料不會被搬動。',
    legacyCounts: '{characters} 個角色 · {drafts} 個草稿',
    legacyClaim: '領取舊版角色資料',
    legacyClaiming: '正在領取…',
    legacyConfirm: '要把 {characters} 個角色與 {drafts} 個草稿領取到「{room}」嗎？這是一次性動作，不會搬動已經屬於其他房間的資料。',
    deleteRoomTitle: '永久刪除房間',
    deleteRoomDescription: '這會永久刪除整個房間工作區，包含所有戰役、跑團與其事件紀錄、隊伍名冊、席位、進行中的戰鬥，以及此房間中的所有角色與草稿。需要保留的資料請先匯出。',
    deleteRoomInventorySummary: '{campaigns} 個戰役 · {characters} 個角色 · {drafts} 個草稿',
    deleteRoomInventoryCampaigns: '戰役',
    deleteRoomInventoryCharacters: '角色',
    deleteRoomInventoryArchivedSuffix: '（已封存）',
    deleteRoomInventoryLoading: '正在載入房間內容清單…',
    deleteRoomInventoryError: '無法載入房間內容清單。',
    deleteRoomAction: '永久刪除房間',
    deleteRoomPrompt: '請輸入「{room}」確認永久刪除。',
    deleteRoomCancel: '取消',
    deleteRoomConfirm: '刪除房間',
    deleteRoomDeleting: '正在刪除…',
  },
} as const satisfies Record<Locale, Record<string, string>>

export type RoomCopy = (typeof COPY)[Locale]

export function roomCopy(locale: Locale): RoomCopy {
  return COPY[locale]
}
