import type { Locale } from '../../i18n/locale'

const copy = {
  'zh-TW': {
    title: '大廳與座位',
    intro: '安排這場 Campaign 的 DM、玩家與旁觀座位。角色選擇只代表下一場開始前的大廳設定。',
    backCampaign: '返回 Campaign',
    missingAccess: '找不到這個 Room 的本機存取資訊，請重新進入 Room。',
    requestFailed: '大廳資料載入失敗。',
    createSeat: '新增座位',
    label: '座位名稱',
    role: '角色',
    dm: 'DM',
    player: '玩家',
    spectator: '旁觀者',
    controller: '控制者',
    unassigned: '未指派',
    connected: '已連線',
    offline: '離線',
    character: '本場角色',
    noCharacter: '不選角色',
    noSeats: '尚未建立座位。',
    archive: '封存座位',
    remove: '刪除座位',
    removeConfirm: '確定刪除此尚未進入 Session 歷史的座位？',
    memberHint: '一般成員只能操作指派給自己的 Human Player Seat。',
    dmSeatHint: 'DM Seat 可由 Room Owner 指派 Human controller，或在開場前建立有限期限的 AI DM credential。',
    activeRosterOnly: '只有 active / inactive 的名冊角色可供 Player Seat 選擇。',
    aiDmController: 'AI DM',
    aiDmTitle: 'AI DM 開場憑證',
    aiDmCreate: '建立 AI DM Token',
    aiDmRotate: 'Rotate AI DM Token',
    aiDmRevoke: '撤銷 AI DM',
    aiDmConfigured: '此 DM Seat 目前已配置 AI DM。既有 token 不會再次顯示；需要新 token 請 rotate。',
    aiDmFiniteHint: '這是有限期限的開場憑證，只能用於這個 Room / Campaign / DM Seat 的開場流程；不是永久 DM 權限。成功開始 Session 後會綁定該場，End / Abandon 後失效。',
    aiDmTokenOnceTitle: 'AI DM Token（僅顯示這一次）',
    aiDmTokenOnceHint: '請現在複製並交給 AI。重新整理或離開頁面後，完整 token 不會再顯示。',
    aiDmExpiresAt: '開場憑證到期時間',
    aiDmExpired: '已到期，請 rotate',
    aiDmCopy: '複製',
    aiDmCopied: '已複製',
    aiDmCopyFailed: '無法自動複製，請手動複製 Token。',
    aiDmFailed: 'AI DM 憑證操作失敗。',
  },
  en: {
    title: 'Lobby & Seats',
    intro: 'Arrange the DM, player, and spectator seats for this Campaign. Character selection is the pre-Session lobby choice only.',
    backCampaign: 'Back to Campaign',
    missingAccess: 'Local access for this Room is missing. Enter the Room again.',
    requestFailed: 'Lobby data could not be loaded.',
    createSeat: 'Add seat',
    label: 'Seat label',
    role: 'Role',
    dm: 'DM',
    player: 'Player',
    spectator: 'Spectator',
    controller: 'Controller',
    unassigned: 'Unassigned',
    connected: 'Connected',
    offline: 'Offline',
    character: 'Active character',
    noCharacter: 'No character',
    noSeats: 'No seats yet.',
    archive: 'Archive seat',
    remove: 'Delete seat',
    removeConfirm: 'Delete this Seat that has not entered Session history?',
    memberHint: 'Members can operate only Human Player Seats assigned to their access session.',
    dmSeatHint: 'The Room Owner can assign a Human DM controller or create a finite-lived AI DM credential before Session start.',
    activeRosterOnly: 'Only active / inactive roster characters can be selected by Player Seats.',
    aiDmController: 'AI DM',
    aiDmTitle: 'AI DM start credential',
    aiDmCreate: 'Create AI DM Token',
    aiDmRotate: 'Rotate AI DM Token',
    aiDmRevoke: 'Revoke AI DM',
    aiDmConfigured: 'This DM Seat currently has an AI DM grant. The existing token is never shown again; rotate if a new token is needed.',
    aiDmFiniteHint: 'This is a finite-lived start credential scoped to this Room, Campaign, and DM Seat; it is not permanent DM authority. After Session start it binds to that Session and is revoked by End / Abandon.',
    aiDmTokenOnceTitle: 'AI DM Token (shown once)',
    aiDmTokenOnceHint: 'Copy it now and give it to the AI. The full token is not shown again after refresh or navigation.',
    aiDmExpiresAt: 'Start credential expires at',
    aiDmExpired: 'Expired — rotate to continue',
    aiDmCopy: 'Copy',
    aiDmCopied: 'Copied',
    aiDmCopyFailed: 'Automatic copy failed. Copy the Token manually.',
    aiDmFailed: 'AI DM credential operation failed.',
  },
} as const

export function lobbyCopy(locale: Locale) {
  return copy[locale]
}
