import type { Locale } from '../../i18n/locale'

const copy = {
  'zh-TW': {
    title: '大廳與座位',
    intro: '安排這場 Campaign 的 DM、玩家與旁觀座位。角色選擇只代表下一場開始前的大廳設定。',
    backCampaign: '返回 Campaign',
    missingAccess: '找不到這個 Room 的本機存取資訊，請重新進入 Room。',
    requestFailed: '大廳資料載入失敗。',
    createSeat: '新增座位',
    label: '座位名稱',
    role: '角色',
    dm: 'DM',
    player: '玩家',
    spectator: '旁觀者',
    controller: '控制者',
    unassigned: '未指派',
    aiReserved: 'AI（尚未開放）',
    connected: '已連線',
    offline: '離線',
    character: '本場角色',
    noCharacter: '不選角色',
    noSeats: '尚未建立座位。',
    archive: '封存座位',
    remove: '刪除座位',
    removeConfirm: '確定刪除此尚未進入 Session 歷史的座位？',
    memberHint: '一般成員只能操作指派給自己的 Human Player Seat。',
    dmSeatHint: 'DM Seat 的 Human controller 只能由 Room Owner 指派或改派。',
    activeRosterOnly: '只有 active / inactive 的名冊角色可供 Player Seat 選擇。',
  },
  en: {
    title: 'Lobby & Seats',
    intro: 'Arrange the DM, player, and spectator seats for this Campaign. Character selection is the pre-Session lobby choice only.',
    backCampaign: 'Back to Campaign',
    missingAccess: 'Local access for this Room is missing. Enter the Room again.',
    requestFailed: 'Lobby data could not be loaded.',
    createSeat: 'Add seat',
    label: 'Seat label',
    role: 'Role',
    dm: 'DM',
    player: 'Player',
    spectator: 'Spectator',
    controller: 'Controller',
    unassigned: 'Unassigned',
    aiReserved: 'AI (not available yet)',
    connected: 'Connected',
    offline: 'Offline',
    character: 'Active character',
    noCharacter: 'No character',
    noSeats: 'No seats yet.',
    archive: 'Archive seat',
    remove: 'Delete seat',
    removeConfirm: 'Delete this Seat that has not entered Session history?',
    memberHint: 'Members can operate only Human Player Seats assigned to their access session.',
    dmSeatHint: 'Only the Room Owner can assign or reassign the Human controller of a DM Seat.',
    activeRosterOnly: 'Only active / inactive roster characters can be selected by Player Seats.',
  },
} as const

export function lobbyCopy(locale: Locale) {
  return copy[locale]
}
