import type { Locale } from '../../i18n/locale'
import { localizedSessionRequestMessage } from '../../i18n/sessionMessages'
import { SessionApiError } from '../../api/sessions'

const copy = {
  'zh-TW': {
    locale: 'zh-TW' as const,
    title: '進行中的 Session',
    intro: '本場參與角色在加入時固定；座位控制者可變更，但不會替換已加入的角色。',
    missingAccess: '找不到這個 Room 的本機存取資訊，請重新進入 Room。',
    loadingFailed: 'Session 資料載入失敗。',
    backLobby: '返回大廳',
    start: '開始 Session',
    starting: '正在開始…',
    resume: '繼續 Session',
    activeHint: '這個 Campaign 已有進行中的 Session。',
    participants: '參與者',
    noParticipants: '尚無參與者。',
    dm: 'DM',
    player: '玩家',
    spectator: '旁觀者',
    noCharacter: '無本場角色',
    lateJoin: '中途加入',
    lateJoinSeat: '選擇 Player Seat',
    noLateJoinSeats: '目前沒有可加入的 Player Seat。',
    join: '加入 Session',
    end: '結束 Session',
    endConfirm: '確定正常結束這場 Session？角色目前狀態會原樣保留。',
    abandon: '放棄 Session',
    abandonConfirm: '確定將這場 Session 標記為 abandoned？這不會指派新的 DM。',
    active: '進行中',
    ended: '已結束',
    abandoned: '已放棄',
    currentDmHint: '只有本場固定的 current DM Controller 可以中途加入與正常結束 Session。',
    ownerAbandonHint: 'Room Owner 若不是本場 DM，只能 Abandon，不能接管或正常 End。',
    eventReconnecting: 'Session 更新連線暫時中斷，正在重新連線…',
    eventDisconnected: '已停止接收 Session 更新，請重新進入 Room 或重新整理頁面。',
    requestFailed: 'Session 操作失敗。',
    aiControlTitle: 'AI 控制',
    aiHandoffInstruction: '暫時交接指示（選填）',
    aiHandoffInstructionPlaceholder: '例如：保護法師，保留最後一個二環法術位。',
    letAiControl: '交給 AI 控制',
    aiControlling: '此 Player Seat 目前由 AI 控制。',
    takeBackControl: '取回控制權',
    takeBackExactOriginHint: '自助取回只限當初交給 AI 的同一個 Room 存取 session。換了瀏覽器或原 session 已失效時，請由 Owner / DM 使用下方管理恢復。',
    aiTokenOnceTitle: 'AI Controller Token（僅顯示一次）',
    aiTokenOnceHint: '請現在複製並交給 AI Controller。重新整理或離開此頁後不會再次顯示明文 token。',
    aiCopyToken: '複製 Token',
    aiTokenCopied: '已複製',
    aiCopyFailed: '無法複製 Token，請手動選取內容。',
    aiRecoveryTitle: '管理恢復',
    aiRecoveryHint: '原 handoff session 遺失或失效時，Owner / DM 可將此 Seat 明確重新指派給一個目前有效的 Human Room session。',
    aiRecoveryTarget: '恢復給',
    aiRecoveryChoose: '選擇 Human Controller',
    aiRecoverToHuman: '重新指派給 Human',
    aiConnected: '在線',
    aiOffline: '離線',
    aiTakeBackFailedRecovery: '無法自助取回。只有原 handoff 的有效 Room session 可以自助取回；請由 Owner / DM 使用管理恢復。',
    aiControllerFailed: 'AI 控制操作失敗，請重新載入目前 Seat 狀態後再試。',
    mainStage: '主舞台',
    stageEmpty: 'DM 尚未設定舞台內容。',
    stageTextLabel: '舞台文字',
    stageImageLabel: '舞台圖片（PNG / JPEG / WebP）',
    stageSave: '更新舞台',
    stageClear: '清除舞台',
    stageSaving: '儲存中…',
    tableCharacters: '本場角色',
    chat: '聊天',
    dice: '骰子',
    log: '紀錄',
    noMessages: '目前還沒有桌內訊息。',
    composerKind: '類型',
    composerSubject: '角色',
    dialogue: '角色對話',
    action: '行動',
    ooc: '場外 OOC',
    whisper: '私訊 DM',
    narration: 'DM 敘事',
    send: '送出',
    sending: '送出中…',
    composerPlaceholder: '輸入內容；也可使用 /action、/check、/search、/whisper、/ooc。',
    checkDeferred: '檢定意圖已送出；正式檢定仍需由 DM 建立，不會自動擲骰。',
    subjectRequired: '角色對話與行動必須先選擇本場 Player Seat。',
    dicePlaceholder: '選擇正式檢定或便利骰；正式結果由 Server authoritative 流程產生。',
    dmProxy: 'DM 代理',
    whisperPrivate: '僅你與 DM',
    checkRequestTitle: '要求檢定',
    checkIntentLabel: '檢定意圖',
    checkTargets: '目標角色',
    checkType: '檢定類型',
    checkChooseType: '請選擇類型',
    checkAbilityType: '能力檢定',
    checkSkillType: '技能檢定',
    checkSaveType: '豁免檢定',
    checkOtherType: '其他正式骰',
    checkAbility: '能力值',
    checkSkill: '技能',
    checkDc: 'DC（可留空）',
    checkModifier: '擲骰模式',
    checkNormal: '正常',
    checkAdvantage: '優勢',
    checkDisadvantage: '劣勢',
    checkAdjustment: '額外調整 ±N',
    checkVisibility: '結果可見性',
    checkPublic: '公開',
    checkRollerDm: '擲骰者 + DM',
    checkDmOnly: '僅 DM',
    checkLabel: '說明',
    checkSubmit: '建立檢定',
    checkSubmitting: '建立中…',
    checkCreated: '已建立 {count} 個正式 RollRequest。',
    rollRequestsTitle: '正式檢定',
    rollNoRequests: '目前沒有可見的正式 RollRequest。',
    rollPending: '等待擲骰',
    rollResolved: '已完成',
    rollCancelled: '已取消',
    rollButton: '擲正式骰',
    rolling: '擲骰中…',
    rollHidden: '結果已送交 DM；此結果對玩家隱藏。',
    rollTotal: '總值',
    rollPhysicalDice: '實體骰原始 d20',
    rollPhysicalSubmit: '提交實體骰',
    quickDiceTitle: '便利骰',
    quickTarget: '擲骰角色',
    quickCount: '骰子數量',
    quickSides: '骰面',
    quickAdjustment: '調整值',
    quickRoll: '擲便利骰',
    quickRolling: '擲骰中…',
    quickResult: '便利骰結果',
  },
  en: {
    locale: 'en' as const,
    title: 'Active Session',
    intro: 'A participant’s active character is fixed when they join. Seat control may change, but it does not replace that character.',
    missingAccess: 'Local access for this Room is missing. Enter the Room again.',
    loadingFailed: 'Session data could not be loaded.',
    backLobby: 'Back to Lobby',
    start: 'Start Session',
    starting: 'Starting…',
    resume: 'Resume Session',
    activeHint: 'This Campaign already has an active Session.',
    participants: 'Participants',
    noParticipants: 'No participants yet.',
    dm: 'DM',
    player: 'Player',
    spectator: 'Spectator',
    noCharacter: 'No active character',
    lateJoin: 'Late Join',
    lateJoinSeat: 'Choose Player Seat',
    noLateJoinSeats: 'No Player Seat is currently eligible to join.',
    join: 'Join Session',
    end: 'End Session',
    endConfirm: 'End this Session normally? Current Character State will be preserved exactly.',
    abandon: 'Abandon Session',
    abandonConfirm: 'Mark this Session abandoned? This does not assign a replacement DM.',
    active: 'Active',
    ended: 'Ended',
    abandoned: 'Abandoned',
    currentDmHint: 'Only this Session’s fixed current DM Controller may Late Join or End it normally.',
    ownerAbandonHint: 'A Room Owner who is not the current DM may Abandon, but cannot take over or End normally.',
    eventReconnecting: 'Session updates are temporarily disconnected. Reconnecting…',
    eventDisconnected: 'Session updates have stopped. Re-enter the Room or refresh this page.',
    requestFailed: 'Session operation failed.',
    aiControlTitle: 'AI Control',
    aiHandoffInstruction: 'Temporary handoff instruction (optional)',
    aiHandoffInstructionPlaceholder: 'Example: protect the wizard and save the last 2nd-level spell slot.',
    letAiControl: 'Let AI Control',
    aiControlling: 'This Player Seat is currently AI controlled.',
    takeBackControl: 'Take Back Control',
    takeBackExactOriginHint: 'Self-service Take Back only works from the exact Room access session that handed control to AI. If that browser/session is gone, use Owner / DM recovery below.',
    aiTokenOnceTitle: 'AI Controller Token (shown once)',
    aiTokenOnceHint: 'Copy this now and give it to the AI Controller. Plaintext is not shown again after refresh or navigation.',
    aiCopyToken: 'Copy Token',
    aiTokenCopied: 'Copied',
    aiCopyFailed: 'Could not copy the token. Select and copy it manually.',
    aiRecoveryTitle: 'Administrative Recovery',
    aiRecoveryHint: 'If the handoff origin is lost or revoked, an Owner / DM can explicitly reassign this Seat to a currently valid Human Room session.',
    aiRecoveryTarget: 'Recover to',
    aiRecoveryChoose: 'Choose Human Controller',
    aiRecoverToHuman: 'Reassign to Human',
    aiConnected: 'Connected',
    aiOffline: 'Offline',
    aiTakeBackFailedRecovery: 'Self-service Take Back failed. Only the exact still-active handoff origin can do it; use Owner / DM recovery instead.',
    aiControllerFailed: 'AI control operation failed. Reload current Seat state and try again.',
    mainStage: 'Main Stage',
    stageEmpty: 'The DM has not set the Stage yet.',
    stageTextLabel: 'Stage text',
    stageImageLabel: 'Stage image (PNG / JPEG / WebP)',
    stageSave: 'Update Stage',
    stageClear: 'Clear Stage',
    stageSaving: 'Saving…',
    tableCharacters: 'Table Characters',
    chat: 'Chat',
    dice: 'Dice',
    log: 'Log',
    noMessages: 'No in-session messages yet.',
    composerKind: 'Type',
    composerSubject: 'Character',
    dialogue: 'Character Dialogue',
    action: 'Action',
    ooc: 'OOC',
    whisper: 'Whisper DM',
    narration: 'DM Narration',
    send: 'Send',
    sending: 'Sending…',
    composerPlaceholder: 'Type here; /action, /check, /search, /whisper, and /ooc are supported.',
    checkDeferred: 'Check intent sent. A formal RollRequest still requires the DM and nothing auto-rolls.',
    subjectRequired: 'Character Dialogue and Action require an explicit Player Seat.',
    dicePlaceholder: 'Choose a formal check or convenience roll; formal results use the server-authoritative flow.',
    dmProxy: 'DM proxy',
    whisperPrivate: 'You + DM only',
    checkRequestTitle: 'Request Check',
    checkIntentLabel: 'Check intent',
    checkTargets: 'Targets',
    checkType: 'Check type',
    checkChooseType: 'Choose a type',
    checkAbilityType: 'Ability Check',
    checkSkillType: 'Skill Check',
    checkSaveType: 'Saving Throw',
    checkOtherType: 'Other formal roll',
    checkAbility: 'Ability',
    checkSkill: 'Skill',
    checkDc: 'DC (optional)',
    checkModifier: 'Roll mode',
    checkNormal: 'Normal',
    checkAdvantage: 'Advantage',
    checkDisadvantage: 'Disadvantage',
    checkAdjustment: 'Adjustment ±N',
    checkVisibility: 'Result visibility',
    checkPublic: 'Public',
    checkRollerDm: 'Roller + DM',
    checkDmOnly: 'DM only',
    checkLabel: 'Label',
    checkSubmit: 'Create Check',
    checkSubmitting: 'Creating…',
    checkCreated: 'Created {count} formal RollRequest(s).',
    rollRequestsTitle: 'Formal Rolls',
    rollNoRequests: 'No visible formal RollRequests yet.',
    rollPending: 'Waiting to roll',
    rollResolved: 'Resolved',
    rollCancelled: 'Cancelled',
    rollButton: 'Roll formally',
    rolling: 'Rolling…',
    rollHidden: 'Result sent to the DM. This result is hidden from the Player.',
    rollTotal: 'Total',
    rollPhysicalDice: 'Physical raw d20',
    rollPhysicalSubmit: 'Submit physical dice',
    quickDiceTitle: 'Quick Dice',
    quickTarget: 'Rolling character',
    quickCount: 'Dice count',
    quickSides: 'Die sides',
    quickAdjustment: 'Adjustment',
    quickRoll: 'Roll Quick Dice',
    quickRolling: 'Rolling…',
    quickResult: 'Quick Dice result',
  },
} as const

export type SessionCopy = (typeof copy)[Locale]

export function sessionCopy(locale: Locale): SessionCopy {
  return copy[locale]
}

export function sessionErrorMessage(error: unknown, presentation: SessionCopy): string {
  if (!(error instanceof SessionApiError)) return presentation.requestFailed
  return localizedSessionRequestMessage(
    error.code,
    error.status,
    error.message,
    presentation.locale,
  )
}
