import type { Locale } from '../../i18n/locale'
import { localizedSessionRequestMessage } from '../../i18n/sessionMessages'
import { SessionApiError } from '../../api/sessions'

const copy = {
  'zh-TW': {
    locale: 'zh-TW' as const,
    title: '進行中的 Session',
    intro: '本場參與角色在加入時固定；座位控制者可變更，但不會替換已加入的角色。',
    missingAccess: '找不到這個 Room 的本機存取資訊，請重新進入 Room。',
    loadingFailed: 'Session 資料載入失敗。',
    backLobby: '返回大廳',
    cardWidthExpand: '展開為寬螢幕',
    cardWidthDefault: '還原預設寬度',
    resizeCard: '調整跑團桌面寬度',
    resizeCardHint: '拖曳調整寬度，雙擊切換預設／最大寬度',
    start: '開始 Session',
    starting: '正在開始…',
    resume: '繼續 Session',
    activeHint: '這個 Campaign 已有進行中的 Session。',
    participants: '參與者',
    noParticipants: '尚無參與者。',
    dm: 'DM',
    player: '玩家',
    spectator: '旁觀者',
    noCharacter: '無本場角色',
    lateJoin: '中途加入',
    lateJoinSeat: '選擇 Player Seat',
    noLateJoinSeats: '目前沒有可加入的 Player Seat。',
    join: '加入 Session',
    end: '結束 Session',
    endConfirm: '確定正常結束這場 Session？角色目前狀態會原樣保留。',
    abandon: '放棄 Session',
    abandonConfirm: '確定將這場 Session 標記為 abandoned？這不會指派新的 DM。',
    active: '進行中',
    ended: '已結束',
    abandoned: '已放棄',
    currentDmHint: '只有本場固定的 current DM Controller 可以中途加入與正常結束 Session。',
    ownerAbandonHint: 'Room Owner 若不是本場 DM，只能 Abandon，不能接管或正常 End。',
    eventReconnecting: 'Session 更新連線暫時中斷，正在重新連線…',
    eventDisconnected: '已停止接收 Session 更新，請重新進入 Room 或重新整理頁面。',
    requestFailed: 'Session 操作失敗。',
    aiControlTitle: 'AI 控制',
    aiHandoffInstruction: '暫時交接指示（選填）',
    aiHandoffInstructionPlaceholder: '例如：保護法師，保留最後一個二環法術位。',
    letAiControl: '交給 AI 控制',
    aiControlling: '此 Player Seat 目前由 AI 控制。',
    takeBackControl: '取回控制權',
    takeBackExactOriginHint: '自助取回只限當初交給 AI 的同一個 Room 存取 session。換了瀏覽器或原 session 已失效時，請由 Owner / DM 使用下方管理恢復。',
    aiTokenOnceTitle: 'AI Controller Token（僅顯示一次）',
    aiTokenOnceHint: '請現在複製並交給 AI Controller。重新整理或離開此頁後不會再次顯示明文 token。',
    aiCopyToken: '複製',
    aiTokenCopied: '已複製',
    aiCopyFailed: '無法複製 Token，請手動選取內容。',
    aiJoinKitTitle: 'AI Join Kit',
    aiJoinKitHint: '把整份 kit 交給 AI；完整操作規則由 server guide 提供。Token 只顯示一次，請勿轉傳。',
    aiJoinKitCopy: '複製 Join Kit',
    aiJoinKitCopied: '已複製 Join Kit',
    aiJoinKitDownload: '下載 .txt',
    aiRecoveryTitle: '管理恢復',
    aiRecoveryHint: '原 handoff session 遺失或失效時，Owner / DM 可將此 Seat 明確重新指派給一個目前有效的 Human Room session。',
    aiRecoveryTarget: '恢復給',
    aiRecoveryChoose: '選擇 Human Controller',
    aiRecoverToHuman: '重新指派給 Human',
    aiConnected: '在線',
    aiOffline: '離線',
    aiTakeBackFailedRecovery: '無法自助取回。只有原 handoff 的有效 Room session 可以自助取回；請由 Owner / DM 使用管理恢復。',
    aiControllerFailed: 'AI 控制操作失敗，請重新載入目前 Seat 狀態後再試。',
    mainStage: '主舞台',
    stageEmpty: 'DM 尚未設定舞台內容。',
    stageTextLabel: '舞台文字',
    stageImageLabel: '舞台圖片（PNG / JPEG / WebP）',
    stageSave: '更新舞台',
    stageClear: '清除舞台',
    stageSaving: '儲存中…',
    tableCharacters: '本場角色',
    chat: '聊天',
    dice: '骰子',
    log: '紀錄',
    noMessages: '目前還沒有桌內訊息。',
    system: '系統',
    rollPrompt: 'DM 要求 {targets}進行{check}{details}{label}。',
    rollPromptCheckWithRef: '{ref}（{type}）',
    rollPromptDetails: '，{details}',
    rollPromptDetailSeparator: '、',
    rollPromptAdjustment: '調整 {adjustment}',
    rollPromptLabel: '：{label}',
    rollPromptTargetSeparator: '、',
    composerKind: '類型',
    composerSubject: '角色',
    dialogue: '角色對話',
    action: '行動',
    ooc: '場外 OOC',
    whisper: '私訊 DM',
    narration: 'DM 敘事',
    chatTextColor: '發言顏色',
    selectChatColor: '選擇發言顏色（16色）',
    close: '關閉',
    send: '送出',
    sending: '送出中…',
    composerPlaceholder: '輸入內容；也可使用 /action、/check、/search、/whisper、/ooc。',
    checkDeferred: '檢定意圖已送出；正式檢定仍需由 DM 建立，不會自動擲骰。',
    subjectRequired: '角色對話與行動必須先選擇本場 Player Seat。',
    dicePlaceholder: '選擇正式檢定或便利骰；正式結果由 Server authoritative 流程產生。',
    dmProxy: 'DM 代理',
    whisperPrivate: '僅你與 DM',
    checkRequestTitle: '要求檢定',
    checkIntentLabel: '檢定意圖',
    checkTargets: '目標角色',
    checkType: '檢定類型',
    checkChooseType: '請選擇類型',
    checkAbilityType: '能力檢定',
    checkSkillType: '技能檢定',
    checkSaveType: '豁免檢定',
    checkOtherType: '其他正式骰',
    checkInitiativeType: '先攻檢定',
    checkAttackType: '攻擊',
    checkDeathSaveType: '死亡豁免',
    checkAbility: '能力值',
    checkSkill: '技能',
    checkDc: 'DC（可留空）',
    checkModifier: '擲骰模式',
    checkNormal: '正常',
    checkAdvantage: '優勢',
    checkDisadvantage: '劣勢',
    checkAdjustment: '額外調整 ±N',
    checkVisibility: '結果可見性',
    checkPublic: '公開',
    checkRollerDm: '擲骰者 + DM',
    checkDmOnly: '僅 DM',
    checkLabel: '說明',
    checkSubmit: '建立檢定',
    checkSubmitting: '建立中…',
    checkCreated: '已建立 {count} 個正式 RollRequest。',
    rollRequestsTitle: '正式檢定',
    rollNoRequests: '目前沒有可見的正式 RollRequest。',
    rollPending: '等待擲骰',
    rollResolved: '已完成',
    rollCancelled: '已取消',
    rollButton: '擲正式骰',
    rolling: '擲骰中…',
    rollHidden: '結果已送交 DM；此結果對玩家隱藏。',
    rollTotal: '總值',
    rollPhysicalDice: '實體骰原始 d20',
    rollPhysicalSubmit: '提交實體骰',
    quickDiceTitle: '便利骰',
    quickTarget: '擲骰角色',
    quickCount: '骰子數量',
    quickSides: '骰面',
    quickAdjustment: '調整值',
    quickRoll: '擲便利骰',
    quickRolling: '擲骰中…',
    quickResult: '便利骰結果',
    checkLabelPlaceholder: '例如：傾聽門後的動靜',
    abilityStr: '力量 (STR)',
    abilityDex: '敏捷 (DEX)',
    abilityCon: '體質 (CON)',
    abilityInt: '智力 (INT)',
    abilityWis: '感知 (WIS)',
    abilityCha: '魅力 (CHA)',
    skillAcrobatics: '特技 (Acrobatics)',
    skillAnimalHandling: '馴獸 (Animal Handling)',
    skillArcana: '奧秘 (Arcana)',
    skillAthletics: '運動 (Athletics)',
    skillDeception: '欺瞞 (Deception)',
    skillHistory: '歷史 (History)',
    skillInsight: '洞悉 (Insight)',
    skillIntimidation: '威嚇 (Intimidation)',
    skillInvestigation: '調查 (Investigation)',
    skillMedicine: '醫藥 (Medicine)',
    skillNature: '自然 (Nature)',
    skillPerception: '察覺 (Perception)',
    skillPerformance: '表演 (Performance)',
    skillPersuasion: '遊說 (Persuasion)',
    skillReligion: '宗教 (Religion)',
    skillSleightOfHand: '巧手 (Sleight of Hand)',
    skillStealth: '隱匿 (Stealth)',
    skillSurvival: '求生 (Survival)',
    combatTitle: '戰鬥',
    combatRound: '第 {round} 輪',
    combatPreInitiative: '戰鬥準備中',
    combatAwaitingInitiative: '等待先攻',
    combatCurrentTurn: '目前回合',
    combatYourTurn: '輪到你了',
    combatInitiativeHeading: '先攻順序',
    combatantsHeading: '戰鬥者名冊',
    combatHostile: '敵對',
    combatActionShort: '動作',
    combatBonusActionShort: '附贈',
    combatReactionShort: '反應',
    combatAttacks: '攻擊',
    combatPositionNote: '位置附註',
    combatInjuryHealthy: '狀態良好',
    combatInjuryWounded: '受傷',
    combatInjuryCritical: '重傷',
    combatInjuryDown: '倒地不起',
    combatStatusActive: '活躍',
    combatStatusWithdrawn: '已撤退',
    combatStatusDown: '倒地',
    combatStatusDead: '死亡',
    combatStatusRemoved: '已移除',
    combatStatusUnconscious: '昏迷',
    combatStatusSurrendered: '已投降',
    combatStatusFled: '已逃離',
    combatDodging: '閃避中',
    combatHp: 'HP',
    combatAc: 'AC',
    combatNoCombatants: '目前無戰鬥者資訊。',
    combatDmNotes: 'DM 筆記',
    combatStart: '開始戰鬥',
    combatEnd: '結束戰鬥',
    combatEndConfirm: '確定要結束戰鬥嗎？',
    combatAddEnemyHeading: '新增敵人',
    combatModeSrdMonster: 'SRD 怪物',
    combatModeQuickEnemy: '快速敵人',
    combatMonsterPickerLabel: '選擇怪物',
    combatMonsterPickerPlaceholder: '搜尋怪物名稱或 CR…',
    combatDisplayName: '自訂名稱（選填）',
    combatDisplayNamePlaceholder: '例如：地精斥候隊長',
    combatVisibility: '能見度',
    combatVisibilityPublic: '公開',
    combatVisibilityHidden: '隱藏',
    combatPositionNotePlaceholder: '例如：站在北側石柱旁',
    combatQuickEnemyName: '名稱',
    combatQuickEnemyAc: 'AC',
    combatQuickEnemyMaxHp: '最大 HP',
    combatQuickEnemyAttackName: '攻擊名稱（選填）',
    combatQuickEnemyAttackBonus: '命中加值（選填）',
    combatQuickEnemyDamage: '傷害（選填）',
    combatQuickEnemyDamagePlaceholder: '1d6+2',
    combatAddEnemyButton: '加入戰鬥',
    combatAddingEnemy: '加入中…',
    combatRequestInitiative: '要求擲先攻',
    combatRequestingInitiative: '要求中…',
    combatRollInitiative: '擲先攻',
    combatRollingInitiative: '擲骰中…',
    combatFinalizeInitiative: '確認先攻順序',
    combatFinalizingInitiative: '確認中…',
    combatAdvanceTurn: '推進回合',
    combatAdvancingTurn: '推進中…',
    combatAwaitingRollHint: '等待所有戰鬥者完成先攻擲骰',
    combatActionBarHeading: '快速動作',
    combatWaitingForTurn: '等待 {name} 的回合',
    combatActionKindLabel: '動作類型',
    combatActionKindAttack: '攻擊',
    combatActionKindGrapple: '擒抱',
    combatActionKindShoveProne: '推撞（倒地）',
    combatActionKindShovePush: '推撞（推開）',
    combatActionKindEscapeGrapple: '脫離擒抱',
    combatActionKindSpell: '法術',
    combatAttackLabel: '攻擊',
    combatSpellLabel: '法術',
    combatSpellSlotLevel: '環階',
    combatTargetLabel: '目標',
    combatRangeConfirmed: '射程已確認',
    combatRequestAttack: '宣告攻擊',
    combatCastSpell: '施放法術',
    combatSpellResolved: '法術已解決',
    combatSpellModeAttack: '法術攻擊',
    combatSpellModeSave: '豁免法術',
    combatSpellModeHeal: '治療法術',
    combatSpellModeUtility: '功能法術',
    combatRollAttack: '擲攻擊骰',
    combatAwaitingAdjudication: '等待 DM 裁定',
    combatActionSpentWaitingDm: '主要動作已用完，等待 DM 推進回合',
    combatAttackHit: '命中',
    combatAttackMiss: '未命中',
    combatAttackCritical: '爆擊',
    combatAttackDamage: '傷害 {damage}',
    combatPendingAttackRollsHeading: '待擲攻擊',
    combatPendingRollsHeading: '待擲戰鬥骰',
    combatRollPending: '擲骰',
    combatRollTypeAttack: '攻擊',
    combatRollTypeSavingThrow: '豁免檢定',
    combatRollTypeDeathSave: '死亡豁免',
    combatRollTypeConcentration: '專注檢定',
    combatRollTypeGrapple: '擒抱對抗',
    combatRollTypeShove: '推撞對抗',
    combatRollTypeEscapeGrapple: '脫離擒抱對抗',
    combatSavingThrowResult: '豁免總值 {total}',
    combatSaveSuccess: '成功',
    combatSaveFailure: '失敗',
    combatSaveAutoFail: '自動失敗',
    combatDeathSaveResult: '死亡豁免 d20 {d20} · 成功 {successes} / 失敗 {failures}',
    combatDeathSaveStable: '已穩定',
    combatDeathSaveDead: '死亡',
    combatConcentrationResult: '專注檢定 {total} 對 DC {dc}',
    combatConcentrationKept: '維持專注',
    combatConcentrationLost: '失去專注',
    combatReactionsHeading: '待處理反應',
    combatReactionAccept: '接受',
    combatReactionDecline: '拒絕',
    combatReactionKindOpportunityAttack: '機會攻擊',
    combatReactionKindShield: '護盾術',
    combatReactionKindCounterspell: '反制法術',
    combatReactionKindReady: '準備動作',
    combatReactionKindLegendaryAction: '傳奇動作',
    combatReactionKindOther: '其他反應',
    combatAwaitingDmRuling: '等待 DM 裁定：{kind}',
    combatAdjudicationPanelHeading: 'DM 戰鬥裁定',
    combatAdjudicationEmpty: '目前沒有待處理裁定。',
    combatInRange: '在射程內',
    combatOutOfRange: '超出射程',
    combatInReach: '在觸及距離內',
    combatOutOfReach: '超出觸及距離',
    combatTrigger: '觸發',
    combatNoTrigger: '不觸發',
    combatConfirmTargets: '確認受影響目標',
    combatResolveAoe: '確認範圍效果',
    combatRuling: '裁定',
    combatResolve: '解決',
    combatUnknownCombatant: '未知戰鬥者',
    combatAdjudicationNote: '裁定備註',
    combatAdjudicationKindRange: '射程',
    combatAdjudicationKindReach: '觸及距離',
    combatAdjudicationKindAffectedTargets: '受影響目標',
    combatAdjudicationKindOpportunityAttack: '機會攻擊',
    combatAdjudicationKindSpecial: '特殊裁定',
    combatMonsterControlsHeading: 'DM 敵人控制',
    combatRevealHeading: '對玩家公開',
    combatRevealAc: 'AC',
    combatRevealDescription: '描述',
    combatRevealPositionNote: '位置附註',
    combatMonsterSetHidden: '設為隱藏',
    combatMonsterSetPublic: '設為公開',
    combatMonsterSave: '儲存',
    combatMonsterSaving: '儲存中…',
    combatOutcomeHeading: '結果判定',
    combatOutcomeDead: '死亡',
    combatOutcomeUnconscious: '昏迷',
    combatOutcomeSurrendered: '投降',
    combatOutcomeFled: '逃離',
    combatOutcomeOther: '其他',
    combatOutcomeNote: '結果備註',
    combatOutcomeNotePlaceholder: '選「其他」時必填',
    combatOutcomeSubmit: '套用結果',
    combatOutcomeCurrentTurnHint: '目前輪到此戰鬥者，請先推進回合',
  },
  en: {
    locale: 'en' as const,
    title: 'Active Session',
    intro: 'A participant’s active character is fixed when they join. Seat control may change, but it does not replace that character.',
    missingAccess: 'Local access for this Room is missing. Enter the Room again.',
    loadingFailed: 'Session data could not be loaded.',
    backLobby: 'Back to Lobby',
    cardWidthExpand: 'Expand to Widescreen',
    cardWidthDefault: 'Reset Default Width',
    resizeCard: 'Resize session table',
    resizeCardHint: 'Drag to resize, double-click to toggle default/maximum width',
    start: 'Start Session',
    starting: 'Starting…',
    resume: 'Resume Session',
    activeHint: 'This Campaign already has an active Session.',
    participants: 'Participants',
    noParticipants: 'No participants yet.',
    dm: 'DM',
    player: 'Player',
    spectator: 'Spectator',
    noCharacter: 'No active character',
    lateJoin: 'Late Join',
    lateJoinSeat: 'Choose Player Seat',
    noLateJoinSeats: 'No Player Seat is currently eligible to join.',
    join: 'Join Session',
    end: 'End Session',
    endConfirm: 'End this Session normally? Current Character State will be preserved exactly.',
    abandon: 'Abandon Session',
    abandonConfirm: 'Mark this Session abandoned? This does not assign a replacement DM.',
    active: 'Active',
    ended: 'Ended',
    abandoned: 'Abandoned',
    currentDmHint: 'Only this Session’s fixed current DM Controller may Late Join or End it normally.',
    ownerAbandonHint: 'A Room Owner who is not the current DM may Abandon, but cannot take over or End normally.',
    eventReconnecting: 'Session updates are temporarily disconnected. Reconnecting…',
    eventDisconnected: 'Session updates have stopped. Re-enter the Room or refresh this page.',
    requestFailed: 'Session operation failed.',
    aiControlTitle: 'AI Control',
    aiHandoffInstruction: 'Temporary handoff instruction (optional)',
    aiHandoffInstructionPlaceholder: 'Example: protect the wizard and save the last 2nd-level spell slot.',
    letAiControl: 'Let AI Control',
    aiControlling: 'This Player Seat is currently AI controlled.',
    takeBackControl: 'Take Back Control',
    takeBackExactOriginHint: 'Self-service Take Back only works from the exact Room access session that handed control to AI. If that browser/session is gone, use Owner / DM recovery below.',
    aiTokenOnceTitle: 'AI Controller Token (shown once)',
    aiTokenOnceHint: 'Copy this now and give it to the AI Controller. Plaintext is not shown again after refresh or navigation.',
    aiCopyToken: 'Copy',
    aiTokenCopied: 'Copied',
    aiCopyFailed: 'Could not copy the token. Select and copy it manually.',
    aiJoinKitTitle: 'AI Join Kit',
    aiJoinKitHint: 'Give the whole kit to the AI; the server-hosted guide contains the full operating rules. The token is shown only once; do not forward it.',
    aiJoinKitCopy: 'Copy Join Kit',
    aiJoinKitCopied: 'Join Kit copied',
    aiJoinKitDownload: 'Download .txt',
    aiRecoveryTitle: 'Administrative Recovery',
    aiRecoveryHint: 'If the handoff origin is lost or revoked, an Owner / DM can explicitly reassign this Seat to a currently valid Human Room session.',
    aiRecoveryTarget: 'Recover to',
    aiRecoveryChoose: 'Choose Human Controller',
    aiRecoverToHuman: 'Reassign to Human',
    aiConnected: 'Connected',
    aiOffline: 'Offline',
    aiTakeBackFailedRecovery: 'Self-service Take Back failed. Only the exact still-active handoff origin can do it; use Owner / DM recovery instead.',
    aiControllerFailed: 'AI control operation failed. Reload current Seat state and try again.',
    mainStage: 'Main Stage',
    stageEmpty: 'The DM has not set the Stage yet.',
    stageTextLabel: 'Stage text',
    stageImageLabel: 'Stage image (PNG / JPEG / WebP)',
    stageSave: 'Update Stage',
    stageClear: 'Clear Stage',
    stageSaving: 'Saving…',
    tableCharacters: 'Table Characters',
    chat: 'Chat',
    dice: 'Dice',
    log: 'Log',
    noMessages: 'No in-session messages yet.',
    system: 'System',
    rollPrompt: 'The DM asks {targets} to make {check}{details}{label}.',
    rollPromptCheckWithRef: '{ref} ({type})',
    rollPromptDetails: ' — {details}',
    rollPromptDetailSeparator: ', ',
    rollPromptAdjustment: '{adjustment} adjustment',
    rollPromptLabel: ': {label}',
    rollPromptTargetSeparator: ', ',
    composerKind: 'Type',
    composerSubject: 'Character',
    dialogue: 'Character Dialogue',
    action: 'Action',
    ooc: 'OOC',
    whisper: 'Whisper DM',
    narration: 'DM Narration',
    chatTextColor: 'Chat Color',
    selectChatColor: 'Select Chat Color (16 colors)',
    close: 'Close',
    send: 'Send',
    sending: 'Sending…',
    composerPlaceholder: 'Type here; /action, /check, /search, /whisper, and /ooc are supported.',
    checkDeferred: 'Check intent sent. A formal RollRequest still requires the DM and nothing auto-rolls.',
    subjectRequired: 'Character Dialogue and Action require an explicit Player Seat.',
    dicePlaceholder: 'Choose a formal check or convenience roll; formal results use the server-authoritative flow.',
    dmProxy: 'DM proxy',
    whisperPrivate: 'You + DM only',
    checkRequestTitle: 'Request Check',
    checkIntentLabel: 'Check intent',
    checkTargets: 'Targets',
    checkType: 'Check type',
    checkChooseType: 'Choose a type',
    checkAbilityType: 'Ability Check',
    checkSkillType: 'Skill Check',
    checkSaveType: 'Saving Throw',
    checkOtherType: 'Other formal roll',
    checkInitiativeType: 'Initiative',
    checkAttackType: 'Attack',
    checkDeathSaveType: 'Death Save',
    checkAbility: 'Ability',
    checkSkill: 'Skill',
    checkDc: 'DC (optional)',
    checkModifier: 'Roll mode',
    checkNormal: 'Normal',
    checkAdvantage: 'Advantage',
    checkDisadvantage: 'Disadvantage',
    checkAdjustment: 'Adjustment ±N',
    checkVisibility: 'Result visibility',
    checkPublic: 'Public',
    checkRollerDm: 'Roller + DM',
    checkDmOnly: 'DM only',
    checkLabel: 'Label',
    checkSubmit: 'Create Check',
    checkSubmitting: 'Creating…',
    checkCreated: 'Created {count} formal RollRequest(s).',
    rollRequestsTitle: 'Formal Rolls',
    rollNoRequests: 'No visible formal RollRequests yet.',
    rollPending: 'Waiting to roll',
    rollResolved: 'Resolved',
    rollCancelled: 'Cancelled',
    rollButton: 'Roll formally',
    rolling: 'Rolling…',
    rollHidden: 'Result sent to the DM. This result is hidden from the Player.',
    rollTotal: 'Total',
    rollPhysicalDice: 'Physical raw d20',
    rollPhysicalSubmit: 'Submit physical dice',
    quickDiceTitle: 'Quick Dice',
    quickTarget: 'Rolling character',
    quickCount: 'Dice count',
    quickSides: 'Die sides',
    quickAdjustment: 'Adjustment',
    quickRoll: 'Roll Quick Dice',
    quickRolling: 'Rolling…',
    quickResult: 'Quick Dice result',
    checkLabelPlaceholder: 'e.g. Listen at the door',
    abilityStr: 'Strength (STR)',
    abilityDex: 'Dexterity (DEX)',
    abilityCon: 'Constitution (CON)',
    abilityInt: 'Intelligence (INT)',
    abilityWis: 'Wisdom (WIS)',
    abilityCha: 'Charisma (CHA)',
    skillAcrobatics: 'Acrobatics',
    skillAnimalHandling: 'Animal Handling',
    skillArcana: 'Arcana',
    skillAthletics: 'Athletics',
    skillDeception: 'Deception',
    skillHistory: 'History',
    skillInsight: 'Insight',
    skillIntimidation: 'Intimidation',
    skillInvestigation: 'Investigation',
    skillMedicine: 'Medicine',
    skillNature: 'Nature',
    skillPerception: 'Perception',
    skillPerformance: 'Performance',
    skillPersuasion: 'Persuasion',
    skillReligion: 'Religion',
    skillSleightOfHand: 'Sleight of Hand',
    skillStealth: 'Stealth',
    skillSurvival: 'Survival',
    combatTitle: 'Combat',
    combatRound: 'Round {round}',
    combatPreInitiative: 'Preparing',
    combatAwaitingInitiative: 'Awaiting Initiative',
    combatCurrentTurn: 'Current Turn',
    combatYourTurn: 'Your Turn',
    combatInitiativeHeading: 'Initiative Order',
    combatantsHeading: 'Combatants',
    combatHostile: 'Hostile',
    combatActionShort: 'Action',
    combatBonusActionShort: 'Bonus',
    combatReactionShort: 'Reaction',
    combatAttacks: 'Attacks',
    combatPositionNote: 'Position Note',
    combatInjuryHealthy: 'Healthy',
    combatInjuryWounded: 'Wounded',
    combatInjuryCritical: 'Critical',
    combatInjuryDown: 'Down',
    combatStatusActive: 'Active',
    combatStatusWithdrawn: 'Withdrawn',
    combatStatusDown: 'Down',
    combatStatusDead: 'Dead',
    combatStatusRemoved: 'Removed',
    combatStatusUnconscious: 'Unconscious',
    combatStatusSurrendered: 'Surrendered',
    combatStatusFled: 'Fled',
    combatDodging: 'Dodging',
    combatHp: 'HP',
    combatAc: 'AC',
    combatNoCombatants: 'No combatants available.',
    combatDmNotes: 'DM Notes',
    combatStart: 'Start Combat',
    combatEnd: 'End Combat',
    combatEndConfirm: 'End this combat? Initiative and round progress will be cleared.',
    combatAddEnemyHeading: 'Add Enemy',
    combatModeSrdMonster: 'SRD Monster',
    combatModeQuickEnemy: 'Quick Enemy',
    combatMonsterPickerLabel: 'Choose Monster',
    combatMonsterPickerPlaceholder: 'Search monster name or CR…',
    combatDisplayName: 'Display Name (optional)',
    combatDisplayNamePlaceholder: 'Example: Goblin Scout Captain',
    combatVisibility: 'Visibility',
    combatVisibilityPublic: 'Public',
    combatVisibilityHidden: 'Hidden',
    combatPositionNotePlaceholder: 'Example: Standing near north pillar',
    combatQuickEnemyName: 'Name',
    combatQuickEnemyAc: 'AC',
    combatQuickEnemyMaxHp: 'Max HP',
    combatQuickEnemyAttackName: 'Attack Name (optional)',
    combatQuickEnemyAttackBonus: 'Attack Bonus (optional)',
    combatQuickEnemyDamage: 'Damage (optional)',
    combatQuickEnemyDamagePlaceholder: '1d6+2',
    combatAddEnemyButton: 'Add to Combat',
    combatAddingEnemy: 'Adding…',
    combatRequestInitiative: 'Request Initiative',
    combatRequestingInitiative: 'Requesting…',
    combatRollInitiative: 'Roll Initiative',
    combatRollingInitiative: 'Rolling…',
    combatFinalizeInitiative: 'Finalize Initiative',
    combatFinalizingInitiative: 'Finalizing…',
    combatAdvanceTurn: 'Advance Turn',
    combatAdvancingTurn: 'Advancing…',
    combatAwaitingRollHint: 'Awaiting initiative rolls from all active combatants',
    combatActionBarHeading: 'Quick Action Bar',
    combatWaitingForTurn: "Waiting for {name}'s turn",
    combatActionKindLabel: 'Action kind',
    combatActionKindAttack: 'Attack',
    combatActionKindGrapple: 'Grapple',
    combatActionKindShoveProne: 'Shove (prone)',
    combatActionKindShovePush: 'Shove (push)',
    combatActionKindEscapeGrapple: 'Escape grapple',
    combatActionKindSpell: 'Spell',
    combatAttackLabel: 'Attack',
    combatSpellLabel: 'Spell',
    combatSpellSlotLevel: 'Slot level',
    combatTargetLabel: 'Target',
    combatRangeConfirmed: 'Range confirmed',
    combatRequestAttack: 'Request Attack',
    combatCastSpell: 'Cast Spell',
    combatSpellResolved: 'Spell resolved',
    combatSpellModeAttack: 'Spell attack',
    combatSpellModeSave: 'Save spell',
    combatSpellModeHeal: 'Healing spell',
    combatSpellModeUtility: 'Utility spell',
    combatRollAttack: 'Roll Attack',
    combatAwaitingAdjudication: 'Waiting for DM adjudication',
    combatActionSpentWaitingDm: 'Action spent — waiting for the DM to advance the turn',
    combatAttackHit: 'Hit',
    combatAttackMiss: 'Miss',
    combatAttackCritical: 'Critical',
    combatAttackDamage: 'Damage {damage}',
    combatPendingAttackRollsHeading: 'Pending Attack Rolls',
    combatPendingRollsHeading: 'Pending Combat Rolls',
    combatRollPending: 'Roll',
    combatRollTypeAttack: 'Attack',
    combatRollTypeSavingThrow: 'Saving Throw',
    combatRollTypeDeathSave: 'Death Save',
    combatRollTypeConcentration: 'Concentration',
    combatRollTypeGrapple: 'Grapple contest',
    combatRollTypeShove: 'Shove contest',
    combatRollTypeEscapeGrapple: 'Escape grapple contest',
    combatSavingThrowResult: 'Saving throw total {total}',
    combatSaveSuccess: 'Success',
    combatSaveFailure: 'Failure',
    combatSaveAutoFail: 'Auto-fail',
    combatDeathSaveResult: 'Death Save d20 {d20} · {successes} successes / {failures} failures',
    combatDeathSaveStable: 'Stable',
    combatDeathSaveDead: 'Dead',
    combatConcentrationResult: 'Concentration {total} vs DC {dc}',
    combatConcentrationKept: 'Concentration kept',
    combatConcentrationLost: 'Concentration lost',
    combatReactionsHeading: 'Pending Reactions',
    combatReactionAccept: 'Accept',
    combatReactionDecline: 'Decline',
    combatReactionKindOpportunityAttack: 'Opportunity attack',
    combatReactionKindShield: 'Shield',
    combatReactionKindCounterspell: 'Counterspell',
    combatReactionKindReady: 'Ready',
    combatReactionKindLegendaryAction: 'Legendary action',
    combatReactionKindOther: 'Other reaction',
    combatAwaitingDmRuling: 'Awaiting DM ruling: {kind}',
    combatAdjudicationPanelHeading: 'DM Adjudications',
    combatAdjudicationEmpty: 'No pending adjudications.',
    combatInRange: 'In range',
    combatOutOfRange: 'Out of range',
    combatInReach: 'In reach',
    combatOutOfReach: 'Out of reach',
    combatTrigger: 'Trigger',
    combatNoTrigger: 'No trigger',
    combatConfirmTargets: 'Confirm affected targets',
    combatResolveAoe: 'Resolve AoE',
    combatRuling: 'Ruling',
    combatResolve: 'Resolve',
    combatUnknownCombatant: 'Unknown combatant',
    combatAdjudicationNote: 'Adjudication note',
    combatAdjudicationKindRange: 'Range',
    combatAdjudicationKindReach: 'Reach',
    combatAdjudicationKindAffectedTargets: 'Affected targets',
    combatAdjudicationKindOpportunityAttack: 'Opportunity attack',
    combatAdjudicationKindSpecial: 'Special',
    combatMonsterControlsHeading: 'Enemy controls',
    combatRevealHeading: 'Reveal to Players',
    combatRevealAc: 'AC',
    combatRevealDescription: 'Description',
    combatRevealPositionNote: 'Position note',
    combatMonsterSetHidden: 'Hide from Players',
    combatMonsterSetPublic: 'Show to Players',
    combatMonsterSave: 'Save',
    combatMonsterSaving: 'Saving…',
    combatOutcomeHeading: 'Outcome',
    combatOutcomeDead: 'Dead',
    combatOutcomeUnconscious: 'Unconscious',
    combatOutcomeSurrendered: 'Surrendered',
    combatOutcomeFled: 'Fled',
    combatOutcomeOther: 'Other',
    combatOutcomeNote: 'Outcome note',
    combatOutcomeNotePlaceholder: 'Required when "Other"',
    combatOutcomeSubmit: 'Apply outcome',
    combatOutcomeCurrentTurnHint: 'This combatant has the current turn; advance the turn first',
  },
} as const

export type SessionCopy = (typeof copy)[Locale]

export function sessionCopy(locale: Locale): SessionCopy {
  return copy[locale]
}

export function sessionErrorMessage(error: unknown, presentation: SessionCopy): string {
  if (!(error instanceof SessionApiError)) return presentation.requestFailed
  return localizedSessionRequestMessage(error.code, error.status, error.message, presentation.locale)
}